// Emits src/data/meta.ts: the catalog the home page needs (title, concept,
// category, tagline, question ids for progress) without any question bodies.
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { PATTERNS } from '../src/data/patterns.ts';

const meta = PATTERNS.map((p) => ({
  num: p.num,
  slug: p.slug,
  key: `p${String(p.num).padStart(2, '0')}`,
  title: p.title,
  concept: p.concept,
  category: p.category,
  tagline: p.tagline,
  questionIds: p.questions.map((q) => q.id),
}));

writeFileSync(
  join(process.cwd(), 'src/data/meta.ts'),
  `// GENERATED by scripts/gen-meta.mjs — do not edit by hand.
import type { Category } from './types';

export interface PatternMeta {
  num: number;
  slug: string;
  /** Module key used by loadPattern(). */
  key: string;
  title: string;
  concept: string;
  category: Category;
  tagline: string;
  questionIds: string[];
}

export const PATTERN_META: PatternMeta[] = ${JSON.stringify(meta, null, 2)};

export const ALL_QUESTION_IDS: string[] = PATTERN_META.flatMap((p) => p.questionIds);
export const TOTAL_QUESTIONS = ALL_QUESTION_IDS.length;
`,
);
console.log(`meta for ${meta.length} patterns, ${meta.reduce((n, p) => n + p.questionIds.length, 0)} questions`);
