// Regenerates the generated data modules from src/data/patterns/pNN.ts:
//   - patterns.ts  eager index, used by scripts (validation, meta generation)
//   - loaders.ts   dynamic import per pattern, so the app code-splits
//   - meta.ts      lightweight catalog the home page can render without
//                  pulling in 500 questions
import { readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const root = process.cwd();
const dir = join(root, 'src/data/patterns');
const names = readdirSync(dir)
  .filter((f) => /^p\d{2}\.ts$/.test(f))
  .sort()
  .map((f) => f.replace('.ts', ''));

writeFileSync(
  join(root, 'src/data/patterns.ts'),
  `// GENERATED by scripts/gen-index.mjs — do not edit by hand.
import type { Pattern } from './types';
${names.map((n) => `import { ${n} } from './patterns/${n}';`).join('\n')}

/** All 50 patterns, eagerly loaded. Used by scripts; the app uses loaders.ts. */
export const PATTERNS: Pattern[] = [
${names.map((n) => `  ${n},`).join('\n')}
];

export const TOTAL_QUESTIONS = PATTERNS.reduce((n, p) => n + p.questions.length, 0);
`,
);

writeFileSync(
  join(root, 'src/data/loaders.ts'),
  `// GENERATED by scripts/gen-index.mjs — do not edit by hand.
import type { Pattern } from './types';

/**
 * One dynamic import per pattern, so opening a pattern page fetches only that
 * pattern's questions instead of all 500.
 */
const LOADERS: Record<string, () => Promise<{ default?: Pattern } & Record<string, unknown>>> = {
${names.map((n) => `  ${n}: () => import('./patterns/${n}'),`).join('\n')}
};

export async function loadPattern(key: string): Promise<Pattern | null> {
  const loader = LOADERS[key];
  if (!loader) return null;
  const mod = await loader();
  return (mod[key] as Pattern) ?? null;
}
`,
);
console.log(`indexed ${names.length} patterns`);
