// GENERATED by scripts/gen-index.mjs — do not edit by hand.
import type { Pattern } from './types';

/**
 * One dynamic import per pattern, so opening a pattern page fetches only that
 * pattern's questions instead of all 500.
 */
const LOADERS: Record<string, () => Promise<{ default?: Pattern } & Record<string, unknown>>> = {
  p01: () => import('./patterns/p01'),
  p02: () => import('./patterns/p02'),
  p03: () => import('./patterns/p03'),
  p04: () => import('./patterns/p04'),
  p05: () => import('./patterns/p05'),
  p06: () => import('./patterns/p06'),
  p07: () => import('./patterns/p07'),
  p08: () => import('./patterns/p08'),
  p09: () => import('./patterns/p09'),
  p10: () => import('./patterns/p10'),
  p11: () => import('./patterns/p11'),
  p12: () => import('./patterns/p12'),
  p13: () => import('./patterns/p13'),
  p14: () => import('./patterns/p14'),
  p15: () => import('./patterns/p15'),
  p16: () => import('./patterns/p16'),
  p17: () => import('./patterns/p17'),
  p18: () => import('./patterns/p18'),
  p19: () => import('./patterns/p19'),
  p20: () => import('./patterns/p20'),
  p21: () => import('./patterns/p21'),
  p22: () => import('./patterns/p22'),
  p23: () => import('./patterns/p23'),
  p24: () => import('./patterns/p24'),
  p25: () => import('./patterns/p25'),
  p26: () => import('./patterns/p26'),
  p27: () => import('./patterns/p27'),
  p28: () => import('./patterns/p28'),
  p29: () => import('./patterns/p29'),
  p30: () => import('./patterns/p30'),
  p31: () => import('./patterns/p31'),
  p32: () => import('./patterns/p32'),
  p33: () => import('./patterns/p33'),
  p34: () => import('./patterns/p34'),
  p35: () => import('./patterns/p35'),
  p36: () => import('./patterns/p36'),
  p37: () => import('./patterns/p37'),
  p38: () => import('./patterns/p38'),
  p39: () => import('./patterns/p39'),
  p40: () => import('./patterns/p40'),
  p41: () => import('./patterns/p41'),
  p42: () => import('./patterns/p42'),
  p43: () => import('./patterns/p43'),
  p44: () => import('./patterns/p44'),
  p45: () => import('./patterns/p45'),
  p46: () => import('./patterns/p46'),
  p47: () => import('./patterns/p47'),
  p48: () => import('./patterns/p48'),
  p49: () => import('./patterns/p49'),
  p50: () => import('./patterns/p50'),
};

export async function loadPattern(key: string): Promise<Pattern | null> {
  const loader = LOADERS[key];
  if (!loader) return null;
  const mod = await loader();
  return (mod[key] as Pattern) ?? null;
}
