// GENERATED by scripts/gen-meta.mjs — do not edit by hand.
import type { Category } from './types';

export interface PatternMeta {
  num: number;
  slug: string;
  /** Module key used by loadPattern(). */
  key: string;
  title: string;
  concept: string;
  category: Category;
  tagline: string;
  questionIds: string[];
}

export const PATTERN_META: PatternMeta[] = [
  {
    "num": 1,
    "slug": "find-duplicate-rows",
    "key": "p01",
    "title": "Find Duplicate Rows",
    "concept": "GROUP BY, HAVING",
    "category": "Aggregation & Grouping",
    "tagline": "Decide what \"the same row\" means, then count the groups that hold more than one.",
    "questionIds": [
      "p01-q1",
      "p01-q2",
      "p01-q3",
      "p01-q4",
      "p01-q5",
      "p01-q6",
      "p01-q7",
      "p01-q8",
      "p01-q9",
      "p01-q10"
    ]
  },
  {
    "num": 2,
    "slug": "top-n-records",
    "key": "p02",
    "title": "Top N Records",
    "concept": "ORDER BY, LIMIT",
    "category": "Ranking & Top-N",
    "tagline": "Sort, cut. The interest is entirely in ties, NULLs and what \"top\" means.",
    "questionIds": [
      "p02-q1",
      "p02-q2",
      "p02-q3",
      "p02-q4",
      "p02-q5",
      "p02-q6",
      "p02-q7",
      "p02-q8",
      "p02-q9",
      "p02-q10"
    ]
  },
  {
    "num": 3,
    "slug": "top-n-per-group",
    "key": "p03",
    "title": "Top N Per Group",
    "concept": "ROW_NUMBER() OVER()",
    "category": "Ranking & Top-N",
    "tagline": "The single most-asked SQL interview shape: number rows inside each partition, then filter.",
    "questionIds": [
      "p03-q1",
      "p03-q2",
      "p03-q3",
      "p03-q4",
      "p03-q5",
      "p03-q6",
      "p03-q7",
      "p03-q8",
      "p03-q9",
      "p03-q10"
    ]
  },
  {
    "num": 4,
    "slug": "ranking",
    "key": "p04",
    "title": "Ranking",
    "concept": "RANK()",
    "category": "Ranking & Top-N",
    "tagline": "Olympic ranking: ties share a position and the next position is skipped.",
    "questionIds": [
      "p04-q1",
      "p04-q2",
      "p04-q3",
      "p04-q4",
      "p04-q5",
      "p04-q6",
      "p04-q7",
      "p04-q8",
      "p04-q9",
      "p04-q10"
    ]
  },
  {
    "num": 5,
    "slug": "dense-ranking",
    "key": "p05",
    "title": "Dense Ranking",
    "concept": "DENSE_RANK()",
    "category": "Ranking & Top-N",
    "tagline": "Rank distinct values, not rows — the function behind every \"Nth highest\" question.",
    "questionIds": [
      "p05-q1",
      "p05-q2",
      "p05-q3",
      "p05-q4",
      "p05-q5",
      "p05-q6",
      "p05-q7",
      "p05-q8",
      "p05-q9",
      "p05-q10"
    ]
  },
  {
    "num": 6,
    "slug": "assign-row-numbers",
    "key": "p06",
    "title": "Assign Row Numbers",
    "concept": "ROW_NUMBER()",
    "category": "Window Functions",
    "tagline": "A deterministic sequence per partition — the workhorse behind dedup, pagination and pivoting.",
    "questionIds": [
      "p06-q1",
      "p06-q2",
      "p06-q3",
      "p06-q4",
      "p06-q5",
      "p06-q6",
      "p06-q7",
      "p06-q8",
      "p06-q9",
      "p06-q10"
    ]
  },
  {
    "num": 7,
    "slug": "running-total",
    "key": "p07",
    "title": "Running Total",
    "concept": "SUM() OVER()",
    "category": "Window Functions",
    "tagline": "A cumulative sum that keeps every row — the frame clause is where the meaning lives.",
    "questionIds": [
      "p07-q1",
      "p07-q2",
      "p07-q3",
      "p07-q4",
      "p07-q5",
      "p07-q6",
      "p07-q7",
      "p07-q8",
      "p07-q9",
      "p07-q10"
    ]
  },
  {
    "num": 8,
    "slug": "moving-average",
    "key": "p08",
    "title": "Moving Average",
    "concept": "AVG() OVER()",
    "category": "Window Functions",
    "tagline": "Smooth a noisy series by averaging a sliding window — the frame clause is the whole question.",
    "questionIds": [
      "p08-q1",
      "p08-q2",
      "p08-q3",
      "p08-q4",
      "p08-q5",
      "p08-q6",
      "p08-q7",
      "p08-q8",
      "p08-q9",
      "p08-q10"
    ]
  },
  {
    "num": 9,
    "slug": "previous-row-value",
    "key": "p09",
    "title": "Previous Row Value",
    "concept": "LAG()",
    "category": "Window Functions",
    "tagline": "Pull a value from an earlier row onto this one, so a comparison becomes a subtraction.",
    "questionIds": [
      "p09-q1",
      "p09-q2",
      "p09-q3",
      "p09-q4",
      "p09-q5",
      "p09-q6",
      "p09-q7",
      "p09-q8",
      "p09-q9",
      "p09-q10"
    ]
  },
  {
    "num": 10,
    "slug": "next-row-value",
    "key": "p10",
    "title": "Next Row Value",
    "concept": "LEAD()",
    "category": "Window Functions",
    "tagline": "LAG turned around — reach forward to close intervals, measure durations and detect what happens next.",
    "questionIds": [
      "p10-q1",
      "p10-q2",
      "p10-q3",
      "p10-q4",
      "p10-q5",
      "p10-q6",
      "p10-q7",
      "p10-q8",
      "p10-q9",
      "p10-q10"
    ]
  },
  {
    "num": 11,
    "slug": "first-value-in-group",
    "key": "p11",
    "title": "First Value in Group",
    "concept": "FIRST_VALUE() OVER()",
    "category": "Window Functions",
    "tagline": "Broadcast the group leader onto every row, so each row can be compared to it.",
    "questionIds": [
      "p11-q1",
      "p11-q2",
      "p11-q3",
      "p11-q4",
      "p11-q5",
      "p11-q6",
      "p11-q7",
      "p11-q8",
      "p11-q9",
      "p11-q10"
    ]
  },
  {
    "num": 12,
    "slug": "last-value-in-group",
    "key": "p12",
    "title": "Last Value in Group",
    "concept": "LAST_VALUE() OVER()",
    "category": "Window Functions",
    "tagline": "The function with the famous trap: without an explicit frame it returns the current row.",
    "questionIds": [
      "p12-q1",
      "p12-q2",
      "p12-q3",
      "p12-q4",
      "p12-q5",
      "p12-q6",
      "p12-q7",
      "p12-q8",
      "p12-q9",
      "p12-q10"
    ]
  },
  {
    "num": 13,
    "slug": "nth-highest-salary",
    "key": "p13",
    "title": "Nth Highest Salary",
    "concept": "DENSE_RANK()",
    "category": "Ranking & Top-N",
    "tagline": "The most-asked SQL question of all time. Everything hinges on how you treat duplicates.",
    "questionIds": [
      "p13-q1",
      "p13-q2",
      "p13-q3",
      "p13-q4",
      "p13-q5",
      "p13-q6",
      "p13-q7",
      "p13-q8",
      "p13-q9",
      "p13-q10"
    ]
  },
  {
    "num": 14,
    "slug": "date-difference",
    "key": "p14",
    "title": "Date Difference",
    "concept": "DATEDIFF()",
    "category": "Time Series & Dates",
    "tagline": "Measure spans between dates — where units, inclusivity and dialect differences all bite.",
    "questionIds": [
      "p14-q1",
      "p14-q2",
      "p14-q3",
      "p14-q4",
      "p14-q5",
      "p14-q6",
      "p14-q7",
      "p14-q8",
      "p14-q9",
      "p14-q10"
    ]
  },
  {
    "num": 15,
    "slug": "month-over-month-growth",
    "key": "p15",
    "title": "Month over Month Growth",
    "concept": "LAG() + Calculation",
    "category": "Time Series & Dates",
    "tagline": "Aggregate to the period, fetch the previous period, divide. The gaps are what get you.",
    "questionIds": [
      "p15-q1",
      "p15-q2",
      "p15-q3",
      "p15-q4",
      "p15-q5",
      "p15-q6",
      "p15-q7",
      "p15-q8",
      "p15-q9",
      "p15-q10"
    ]
  },
  {
    "num": 16,
    "slug": "find-missing-records",
    "key": "p16",
    "title": "Find Missing Records",
    "concept": "LEFT JOIN / NOT EXISTS",
    "category": "Joins & Set Logic",
    "tagline": "Anti-join: rows on one side with no counterpart on the other. Three ways to write it, one to avoid.",
    "questionIds": [
      "p16-q1",
      "p16-q2",
      "p16-q3",
      "p16-q4",
      "p16-q5",
      "p16-q6",
      "p16-q7",
      "p16-q8",
      "p16-q9",
      "p16-q10"
    ]
  },
  {
    "num": 17,
    "slug": "find-matching-records",
    "key": "p17",
    "title": "Find Matching Records",
    "concept": "INNER JOIN",
    "category": "Joins & Set Logic",
    "tagline": "The join everyone thinks is easy — until row multiplication doubles the revenue.",
    "questionIds": [
      "p17-q1",
      "p17-q2",
      "p17-q3",
      "p17-q4",
      "p17-q5",
      "p17-q6",
      "p17-q7",
      "p17-q8",
      "p17-q9",
      "p17-q10"
    ]
  },
  {
    "num": 18,
    "slug": "find-non-matching-records",
    "key": "p18",
    "title": "Find Non-Matching Records",
    "concept": "LEFT JOIN / NOT EXISTS",
    "category": "Joins & Set Logic",
    "tagline": "Anti-join in both directions, plus the harder \"matched on key but not on condition\" case.",
    "questionIds": [
      "p18-q1",
      "p18-q2",
      "p18-q3",
      "p18-q4",
      "p18-q5",
      "p18-q6",
      "p18-q7",
      "p18-q8",
      "p18-q9",
      "p18-q10"
    ]
  },
  {
    "num": 19,
    "slug": "conditional-aggregation",
    "key": "p19",
    "title": "Conditional Aggregation",
    "concept": "CASE WHEN + SUM()",
    "category": "Aggregation & Grouping",
    "tagline": "Count and sum subsets in one pass — the technique behind pivots, funnels and cohort tables.",
    "questionIds": [
      "p19-q1",
      "p19-q2",
      "p19-q3",
      "p19-q4",
      "p19-q5",
      "p19-q6",
      "p19-q7",
      "p19-q8",
      "p19-q9",
      "p19-q10"
    ]
  },
  {
    "num": 20,
    "slug": "pivot-unpivot-data",
    "key": "p20",
    "title": "Pivot / Unpivot Data",
    "concept": "PIVOT / UNPIVOT",
    "category": "Reshaping & Text",
    "tagline": "Rows to columns and back. The portable answer is CASE, not the PIVOT keyword.",
    "questionIds": [
      "p20-q1",
      "p20-q2",
      "p20-q3",
      "p20-q4",
      "p20-q5",
      "p20-q6",
      "p20-q7",
      "p20-q8",
      "p20-q9",
      "p20-q10"
    ]
  },
  {
    "num": 21,
    "slug": "customers-without-orders",
    "key": "p21",
    "title": "Customers Without Orders",
    "concept": "LEFT JOIN + IS NULL",
    "category": "Joins & Set Logic",
    "tagline": "The named case of the anti-join — and the one where ON versus WHERE decides the answer.",
    "questionIds": [
      "p21-q1",
      "p21-q2",
      "p21-q3",
      "p21-q4",
      "p21-q5",
      "p21-q6",
      "p21-q7",
      "p21-q8",
      "p21-q9",
      "p21-q10"
    ]
  },
  {
    "num": 22,
    "slug": "products-never-sold",
    "key": "p22",
    "title": "Products Never Sold",
    "concept": "NOT EXISTS",
    "category": "Joins & Set Logic",
    "tagline": "Anti-join from the dimension side, and the place to learn why NOT EXISTS beats NOT IN.",
    "questionIds": [
      "p22-q1",
      "p22-q2",
      "p22-q3",
      "p22-q4",
      "p22-q5",
      "p22-q6",
      "p22-q7",
      "p22-q8",
      "p22-q9",
      "p22-q10"
    ]
  },
  {
    "num": 23,
    "slug": "employee-hierarchy",
    "key": "p23",
    "title": "Employee Hierarchy",
    "concept": "SELF JOIN",
    "category": "Data Quality & Modeling",
    "tagline": "One table, two roles. A self join reads a hierarchy one level at a time.",
    "questionIds": [
      "p23-q1",
      "p23-q2",
      "p23-q3",
      "p23-q4",
      "p23-q5",
      "p23-q6",
      "p23-q7",
      "p23-q8",
      "p23-q9",
      "p23-q10"
    ]
  },
  {
    "num": 24,
    "slug": "overlapping-date-ranges",
    "key": "p24",
    "title": "Overlapping Date Ranges",
    "concept": "SELF JOIN",
    "category": "Time Series & Dates",
    "tagline": "Two intervals overlap when each starts before the other ends. One condition, endlessly misremembered.",
    "questionIds": [
      "p24-q1",
      "p24-q2",
      "p24-q3",
      "p24-q4",
      "p24-q5",
      "p24-q6",
      "p24-q7",
      "p24-q8",
      "p24-q9",
      "p24-q10"
    ]
  },
  {
    "num": 25,
    "slug": "merge-multiple-tables",
    "key": "p25",
    "title": "Merge Multiple Tables",
    "concept": "UNION ALL",
    "category": "Joins & Set Logic",
    "tagline": "Stack rows vertically. UNION ALL unless you can justify the deduplication cost.",
    "questionIds": [
      "p25-q1",
      "p25-q2",
      "p25-q3",
      "p25-q4",
      "p25-q5",
      "p25-q6",
      "p25-q7",
      "p25-q8",
      "p25-q9",
      "p25-q10"
    ]
  },
  {
    "num": 26,
    "slug": "compare-two-tables",
    "key": "p26",
    "title": "Compare Two Tables",
    "concept": "FULL OUTER JOIN",
    "category": "Joins & Set Logic",
    "tagline": "One join that answers \"only in A\", \"only in B\" and \"in both but different\" at once.",
    "questionIds": [
      "p26-q1",
      "p26-q2",
      "p26-q3",
      "p26-q4",
      "p26-q5",
      "p26-q6",
      "p26-q7",
      "p26-q8",
      "p26-q9",
      "p26-q10"
    ]
  },
  {
    "num": 27,
    "slug": "detect-changed-records",
    "key": "p27",
    "title": "Detect Changed Records",
    "concept": "FULL OUTER JOIN",
    "category": "Data Quality & Modeling",
    "tagline": "Change Data Capture without a CDC tool: classify every key as inserted, updated, deleted or unchanged.",
    "questionIds": [
      "p27-q1",
      "p27-q2",
      "p27-q3",
      "p27-q4",
      "p27-q5",
      "p27-q6",
      "p27-q7",
      "p27-q8",
      "p27-q9",
      "p27-q10"
    ]
  },
  {
    "num": 28,
    "slug": "fast-dimension-lookup",
    "key": "p28",
    "title": "Fast Dimension Lookup",
    "concept": "LEFT JOIN",
    "category": "Joins & Set Logic",
    "tagline": "Decorate facts with dimension attributes without losing a single fact row.",
    "questionIds": [
      "p28-q1",
      "p28-q2",
      "p28-q3",
      "p28-q4",
      "p28-q5",
      "p28-q6",
      "p28-q7",
      "p28-q8",
      "p28-q9",
      "p28-q10"
    ]
  },
  {
    "num": 29,
    "slug": "customers-with-multiple-orders",
    "key": "p29",
    "title": "Customers with Multiple Orders",
    "concept": "GROUP BY, HAVING",
    "category": "Aggregation & Grouping",
    "tagline": "Filter groups, not rows. WHERE cannot see an aggregate; HAVING is evaluated after one exists.",
    "questionIds": [
      "p29-q1",
      "p29-q2",
      "p29-q3",
      "p29-q4",
      "p29-q5",
      "p29-q6",
      "p29-q7",
      "p29-q8",
      "p29-q9",
      "p29-q10"
    ]
  },
  {
    "num": 30,
    "slug": "latest-record-per-group",
    "key": "p30",
    "title": "Latest Record Per Group",
    "concept": "ROW_NUMBER()",
    "category": "Ranking & Top-N",
    "tagline": "The most common query in production analytics. Four ways to write it; know why you picked yours.",
    "questionIds": [
      "p30-q1",
      "p30-q2",
      "p30-q3",
      "p30-q4",
      "p30-q5",
      "p30-q6",
      "p30-q7",
      "p30-q8",
      "p30-q9",
      "p30-q10"
    ]
  },
  {
    "num": 31,
    "slug": "top-salary-per-department",
    "key": "p31",
    "title": "Top Salary Per Department",
    "concept": "DENSE_RANK()",
    "category": "Ranking & Top-N",
    "tagline": "The classic per-group top-N, where the whole question is how you handle a tie for first place.",
    "questionIds": [
      "p31-q1",
      "p31-q2",
      "p31-q3",
      "p31-q4",
      "p31-q5",
      "p31-q6",
      "p31-q7",
      "p31-q8",
      "p31-q9",
      "p31-q10"
    ]
  },
  {
    "num": 32,
    "slug": "remove-duplicate-rows",
    "key": "p32",
    "title": "Remove Duplicate Rows",
    "concept": "ROW_NUMBER() + DELETE",
    "category": "Data Quality & Modeling",
    "tagline": "Number within the duplicate key, keep one, delete the rest — and always SELECT before you DELETE.",
    "questionIds": [
      "p32-q1",
      "p32-q2",
      "p32-q3",
      "p32-q4",
      "p32-q5",
      "p32-q6",
      "p32-q7",
      "p32-q8",
      "p32-q9",
      "p32-q10"
    ]
  },
  {
    "num": 33,
    "slug": "replace-null-values",
    "key": "p33",
    "title": "Replace NULL Values",
    "concept": "COALESCE()",
    "category": "Data Quality & Modeling",
    "tagline": "NULL is \"unknown\", not zero. Replacing it is a decision about meaning, not a formatting step.",
    "questionIds": [
      "p33-q1",
      "p33-q2",
      "p33-q3",
      "p33-q4",
      "p33-q5",
      "p33-q6",
      "p33-q7",
      "p33-q8",
      "p33-q9",
      "p33-q10"
    ]
  },
  {
    "num": 34,
    "slug": "find-consecutive-records",
    "key": "p34",
    "title": "Find Consecutive Records",
    "concept": "LAG()",
    "category": "Time Series & Dates",
    "tagline": "Streaks, runs and repeats — flag the breaks with LAG, then accumulate them into group ids.",
    "questionIds": [
      "p34-q1",
      "p34-q2",
      "p34-q3",
      "p34-q4",
      "p34-q5",
      "p34-q6",
      "p34-q7",
      "p34-q8",
      "p34-q9",
      "p34-q10"
    ]
  },
  {
    "num": 35,
    "slug": "detect-gaps-in-sequence",
    "key": "p35",
    "title": "Detect Gaps in Sequence",
    "concept": "ROW_NUMBER() Logic",
    "category": "Time Series & Dates",
    "tagline": "The other half of gaps-and-islands: find what is missing, not what is present.",
    "questionIds": [
      "p35-q1",
      "p35-q2",
      "p35-q3",
      "p35-q4",
      "p35-q5",
      "p35-q6",
      "p35-q7",
      "p35-q8",
      "p35-q9",
      "p35-q10"
    ]
  },
  {
    "num": 36,
    "slug": "cumulative-percentage",
    "key": "p36",
    "title": "Cumulative Percentage",
    "concept": "SUM() OVER()",
    "category": "Window Functions",
    "tagline": "Two windows, one row: a running total over a partition total. The engine of every Pareto chart.",
    "questionIds": [
      "p36-q1",
      "p36-q2",
      "p36-q3",
      "p36-q4",
      "p36-q5",
      "p36-q6",
      "p36-q7",
      "p36-q8",
      "p36-q9",
      "p36-q10"
    ]
  },
  {
    "num": 37,
    "slug": "percent-of-total",
    "key": "p37",
    "title": "Percent of Total",
    "concept": "SUM() OVER()",
    "category": "Window Functions",
    "tagline": "Row value over group total, without a self-join. The question is always: total of what?",
    "questionIds": [
      "p37-q1",
      "p37-q2",
      "p37-q3",
      "p37-q4",
      "p37-q5",
      "p37-q6",
      "p37-q7",
      "p37-q8",
      "p37-q9",
      "p37-q10"
    ]
  },
  {
    "num": 38,
    "slug": "running-count",
    "key": "p38",
    "title": "Running Count",
    "concept": "COUNT() OVER()",
    "category": "Window Functions",
    "tagline": "Cumulative counts: how many so far. Which COUNT you use decides what \"so far\" means.",
    "questionIds": [
      "p38-q1",
      "p38-q2",
      "p38-q3",
      "p38-q4",
      "p38-q5",
      "p38-q6",
      "p38-q7",
      "p38-q8",
      "p38-q9",
      "p38-q10"
    ]
  },
  {
    "num": 39,
    "slug": "distinct-count",
    "key": "p39",
    "title": "Distinct Count",
    "concept": "COUNT(DISTINCT)",
    "category": "Aggregation & Grouping",
    "tagline": "Counting unique things. Non-additive, NULL-skipping, and expensive — three facts that shape every design.",
    "questionIds": [
      "p39-q1",
      "p39-q2",
      "p39-q3",
      "p39-q4",
      "p39-q5",
      "p39-q6",
      "p39-q7",
      "p39-q8",
      "p39-q9",
      "p39-q10"
    ]
  },
  {
    "num": 40,
    "slug": "rolling-7-day-average",
    "key": "p40",
    "title": "Rolling 7-Day Average",
    "concept": "AVG() OVER()",
    "category": "Time Series & Dates",
    "tagline": "The standard smoothing metric — and the standard trap of seven rows not being seven days.",
    "questionIds": [
      "p40-q1",
      "p40-q2",
      "p40-q3",
      "p40-q4",
      "p40-q5",
      "p40-q6",
      "p40-q7",
      "p40-q8",
      "p40-q9",
      "p40-q10"
    ]
  },
  {
    "num": 41,
    "slug": "customer-retention",
    "key": "p41",
    "title": "Customer Retention",
    "concept": "SELF JOIN",
    "category": "Time Series & Dates",
    "tagline": "Did the same person come back? A self join on the entity across two periods.",
    "questionIds": [
      "p41-q1",
      "p41-q2",
      "p41-q3",
      "p41-q4",
      "p41-q5",
      "p41-q6",
      "p41-q7",
      "p41-q8",
      "p41-q9",
      "p41-q10"
    ]
  },
  {
    "num": 42,
    "slug": "scd-type-2-comparison",
    "key": "p42",
    "title": "SCD Type 2 Comparison",
    "concept": "SELF JOIN",
    "category": "Data Quality & Modeling",
    "tagline": "Dimensions that keep history: query as-of a date, compare versions, and close the open row correctly.",
    "questionIds": [
      "p42-q1",
      "p42-q2",
      "p42-q3",
      "p42-q4",
      "p42-q5",
      "p42-q6",
      "p42-q7",
      "p42-q8",
      "p42-q9",
      "p42-q10"
    ]
  },
  {
    "num": 43,
    "slug": "recursive-hierarchy",
    "key": "p43",
    "title": "Recursive Hierarchy",
    "concept": "RECURSIVE CTE",
    "category": "Data Quality & Modeling",
    "tagline": "Walk a tree of unknown depth. Anchor, recursive term, UNION ALL — and always a depth guard.",
    "questionIds": [
      "p43-q1",
      "p43-q2",
      "p43-q3",
      "p43-q4",
      "p43-q5",
      "p43-q6",
      "p43-q7",
      "p43-q8",
      "p43-q9",
      "p43-q10"
    ]
  },
  {
    "num": 44,
    "slug": "split-string-into-rows",
    "key": "p44",
    "title": "Split String into Rows",
    "concept": "STRING_SPLIT()",
    "category": "Reshaping & Text",
    "tagline": "Unpack a comma-separated column into rows — and then argue for fixing the schema.",
    "questionIds": [
      "p44-q1",
      "p44-q2",
      "p44-q3",
      "p44-q4",
      "p44-q5",
      "p44-q6",
      "p44-q7",
      "p44-q8",
      "p44-q9",
      "p44-q10"
    ]
  },
  {
    "num": 45,
    "slug": "find-mode",
    "key": "p45",
    "title": "Find Mode",
    "concept": "GROUP BY, COUNT()",
    "category": "Aggregation & Grouping",
    "tagline": "The most frequent value. Count, then take the maximum count — and decide what to do about ties.",
    "questionIds": [
      "p45-q1",
      "p45-q2",
      "p45-q3",
      "p45-q4",
      "p45-q5",
      "p45-q6",
      "p45-q7",
      "p45-q8",
      "p45-q9",
      "p45-q10"
    ]
  },
  {
    "num": 46,
    "slug": "longest-shortest-value",
    "key": "p46",
    "title": "Longest & Shortest Value",
    "concept": "LENGTH(), MIN(), MAX()",
    "category": "Reshaping & Text",
    "tagline": "Extremes of a derived measure — plus the eternal MAX-versus-ranking distinction.",
    "questionIds": [
      "p46-q1",
      "p46-q2",
      "p46-q3",
      "p46-q4",
      "p46-q5",
      "p46-q6",
      "p46-q7",
      "p46-q8",
      "p46-q9",
      "p46-q10"
    ]
  },
  {
    "num": 47,
    "slug": "string-pattern-matching",
    "key": "p47",
    "title": "String Pattern Matching",
    "concept": "LIKE",
    "category": "Reshaping & Text",
    "tagline": "Wildcards, case, escapes and the index cliff — matching text is easy to write and easy to get wrong.",
    "questionIds": [
      "p47-q1",
      "p47-q2",
      "p47-q3",
      "p47-q4",
      "p47-q5",
      "p47-q6",
      "p47-q7",
      "p47-q8",
      "p47-q9",
      "p47-q10"
    ]
  },
  {
    "num": 48,
    "slug": "find-common-records",
    "key": "p48",
    "title": "Find Common Records",
    "concept": "INTERSECT",
    "category": "Joins & Set Logic",
    "tagline": "Rows present in both result sets. Set semantics: whole rows, NULL-safe, deduplicated.",
    "questionIds": [
      "p48-q1",
      "p48-q2",
      "p48-q3",
      "p48-q4",
      "p48-q5",
      "p48-q6",
      "p48-q7",
      "p48-q8",
      "p48-q9",
      "p48-q10"
    ]
  },
  {
    "num": 49,
    "slug": "find-records-in-a-not-b",
    "key": "p49",
    "title": "Find Records in A Not B",
    "concept": "EXCEPT",
    "category": "Joins & Set Logic",
    "tagline": "Set difference: whole rows, NULL-safe, deduplicated — and the shortest correct reconciliation tool.",
    "questionIds": [
      "p49-q1",
      "p49-q2",
      "p49-q3",
      "p49-q4",
      "p49-q5",
      "p49-q6",
      "p49-q7",
      "p49-q8",
      "p49-q9",
      "p49-q10"
    ]
  },
  {
    "num": 50,
    "slug": "query-performance-analysis",
    "key": "p50",
    "title": "Query Performance Analysis",
    "concept": "EXPLAIN / EXPLAIN ANALYZE",
    "category": "Performance",
    "tagline": "Read the plan, find the row-estimate that is wrong, and fix the cause rather than the symptom.",
    "questionIds": [
      "p50-q1",
      "p50-q2",
      "p50-q3",
      "p50-q4",
      "p50-q5",
      "p50-q6",
      "p50-q7",
      "p50-q8",
      "p50-q9",
      "p50-q10"
    ]
  }
];

export const ALL_QUESTION_IDS: string[] = PATTERN_META.flatMap((p) => p.questionIds);
export const TOTAL_QUESTIONS = ALL_QUESTION_IDS.length;
